//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vJoyConfNet.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("vJoyConfNet.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activating Configuration changes....
        /// </summary>
        internal static string ActivatingConfigurationchanges {
            get {
                return ResourceManager.GetString("ActivatingConfigurationchanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applying configuration for: Device{0:D2}.
        /// </summary>
        internal static string ApplyingConfiguration {
            get {
                return ResourceManager.GetString("ApplyingConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting configuration for: Device{0:D2}.
        /// </summary>
        internal static string DeletingvJoyConfiguration {
            get {
                return ResourceManager.GetString("DeletingvJoyConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done! Waiting for next task....
        /// </summary>
        internal static string DoneWaitingForNextTask {
            get {
                return ResourceManager.GetString("DoneWaitingForNextTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: Something went wrong while parsing: {0}
        ///
        ///{1}.
        /// </summary>
        internal static string ErrorProcessingPreset {
            get {
                return ResourceManager.GetString("ErrorProcessingPreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please install vJoy first!.
        /// </summary>
        internal static string PleaseInstallvJoyFirst {
            get {
                return ResourceManager.GetString("PleaseInstallvJoyFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to presets.
        /// </summary>
        internal static string PresetsFolderName {
            get {
                return ResourceManager.GetString("PresetsFolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing {0}....
        /// </summary>
        internal static string Processing {
            get {
                return ResourceManager.GetString("Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: Unable to access the required registry keys!.
        /// </summary>
        internal static string RegistryError {
            get {
                return ResourceManager.GetString("RegistryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resetting vJoy.
        /// </summary>
        internal static string ResettingvJoy {
            get {
                return ResourceManager.GetString("ResettingvJoy", resourceCulture);
            }
        }
    }
}
